version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/cloudini_foxglove"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/cloudini_web"
    schedule:
      interval: "weekly"
